# Minimal shell, just enough for the llext command tree
CONFIG_SHELL=y
CONFIG_SHELL_CMD_BUFF_SIZE=4224
CONFIG_SHELL_STACK_SIZE=1536
CONFIG_SHELL_BACKEND_SERIAL_TX_RING_BUFFER_SIZE=128
CONFIG_SHELL_BACKEND_SERIAL_RX_RING_BUFFER_SIZE=128
CONFIG_SHELL_HELP=n
CONFIG_SHELL_STATS=n
CONFIG_SHELL_HISTORY=n
CONFIG_SHELL_WILDCARD=n

# No logging: it costs RAM and we don't need it for this experiment
CONFIG_LOG=n

# LLEXT itself
CONFIG_LLEXT=y
CONFIG_LLEXT_SHELL=y
CONFIG_LLEXT_HEAP_SIZE=4
CONFIG_LLEXT_SHELL_MAX_SIZE=2048
CONFIG_LLEXT_IMPORT_ALL_GLOBALS=y
